### ISSUE TITLE
[BUG] Trying to merge with a changed structure (AD node to Base).

### ISSUE THREAD

**Issue by MireilleBF** [ROCKFlows/FromMLWFConfigurationToBPMN#143]
**Describe the bug**
020-07-18 15:06:45 INFO  FileHandler:224 - Preprocessing file : FMA_WF4.xml...
2020-07-18 15:06:45 INFO  FileHandler:224 - Preprocessing file : WF4.bpmn2...
2020-07-18 15:06:45 WARN  XMLManager:484 - Global annotation node not found.
2020-07-18 15:06:45 FATAL Merge:115 - Can't merge the Workflow with the FeatureModel.
java.lang.NullPointerException
	at com.ml2wf.merge.base.BaseMergerImpl.processTask(BaseMergerImpl.java:284)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.ml2wf.merge.base.BaseMergerImpl.mergeWithWF(BaseMergerImpl.java:142)
	at com.ml2wf.cmd.Merge.processMerge(Merge.java:103)
	at com.ml2wf.cmd.Merge.run(Merge.java:116)

**To Reproduce**
TestConflict.java

Here is One example 
The FM
![FMA](https://user-images.githubusercontent.com/18258429/87853288-30de8700-c909-11ea-8e9b-b1d7a492798f.png)

The WF
![WF2](https://user-images.githubusercontent.com/18258429/87853297-3c31b280-c909-11ea-8512-f3b4eaffa99f.png)

**Expected behavior**
no error or explanations according to the examples.

**Comment by NicolasLacroix** [comment]
I am not able to replicate this issue. Can you join the involved files ?

**Comment by MireilleBF** [comment]
[WF2.bpmn2.zip](https://github.com/MireilleBF/FromMLWFConfigurationToBPMN/files/4941838/WF2.bpmn2.zip)

[FMA.xml.zip](https://github.com/MireilleBF/FromMLWFConfigurationToBPMN/files/4941839/FMA.xml.zip)

and a simple merge --meta

All tests are available in Branch ValidationTests
